spring:
  datasource:
    username: admin-prod
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://localhost:5432/dbcompanies
    password: ADd665asdDAS2AASDFHH520aAKOY8
